### ISSUE TITLE
Debian (raspian OS) Daemon load issue

### ISSUE THREAD

**Issue by DogestMaximus** [shermand100/pinode-doge#2]
### Thank you for all of your hard work on this! 
 Pretty incredible and exciting that I finally get to use some of this stuff again:
![image](https://user-images.githubusercontent.com/119521071/213847895-52fe7a76-f833-4b79-8d9f-c77517d6199e.png)

Very small issue I noticed on a Rpi 3B+ which isn't so much an issue with code but more version support and os backwards compatibility.

Device:  RPi3 B+ (likely B Model as well- will also test)
OS: Debian 11 (bullseye)
Issue: PHP 7.3 backwards compatibility

Workaround: Use Debian 10 (buster) still includes PHP 7.3 -ver support (Could simply be linked on the main page temporarily under Rpi3 section).

Summary: Debian 11 (bullseye only uses PHP 7.4 candidate Out of the Box), Debian 11 (bullseye) USB boots fine as expected whereas Debian 10 (buster) USB boot = kernel panic- workaround: boot microSD storage in default slot and configure USB storage as necessary.

![image](https://user-images.githubusercontent.com/119521071/213848450-e2869a65-d558-4560-9f0a-2baefdad843c.png)

Awesome Release!  Very Exciting! Excellent Work!  Still was able to get it to work!
![image](https://user-images.githubusercontent.com/119521071/213848600-d76aa1e4-6f4e-4f50-a447-7d9bb2c8788a.png)

**Comment by shermand100** [comment]
Hi thanks for the feedback. As you can probably see from the commit history this is just a side fork of the main PiNodeXMR project and often doesn't get all the shiny new updates that one does. Sorry.
Although based on your screenshot that does remind me to merge across the new dark mode theme that sorts out the ugliness of the background borders, (It all looks a lot better in light mode)


Anyway, yes what you're talking about was noticed and fixed with the [XMR branch](https://github.com/monero-ecosystem/PiNode-XMR/commit/ecc6d73034be4bbafd15a3a5d74b2e220126ae3e) So I've fixed it in this project as linked below:

Fixed Doge Debian branch: https://github.com/shermand100/pinode-doge/commit/1779a858743b22ce2fa001ac7b120355595ea1fc
Fixed Doge Raspbian branch: https://github.com/shermand100/pinode-doge/commit/fac0337785240e5d73817211146da10a64790637

I'll get it to run a build tonight to make sure it builds ok. We took the approach of not specifying what version of php to install so it just automatically gets and updates to the latest.


As for OS versions, I've had big problems with the XMR project when we Debian went from Buster to Bullseye. As the OS cycle is every 2 years we've opted to move to Ubuntu Server LTS images so we're stable until 2035. When I get a spare week or so I'll look at porting this project over to the LTS OS images too. There are very few changes needed.

**Comment by DogestMaximus** [comment]
Thank you yes I took a look at XMR as well and will take a look at these as well.  I'm learning quite a bit just from going through this code.

I appreciate the information of why everything has migrated to ubuntu- makes perfect sense now for LTS.

Thanks again for your hard work on this- hopefully I'll be more helpful soon as I'm trying to learn as fast as I can.
