### ISSUE TITLE
Armbian Debian 11 no longer supported php-common script issue

### ISSUE THREAD

**Issue by DogestMaximus** [shermand100/pinode-doge#3]
I noticed while attempting to download Armbian that Bullseye is no longer supported.  Even when attempting to build it has been removed from the Armbian Repo apparently.

php-common lacks a space before the -y in the script I believe- I installed it manually but there are other non-compliance issues with Ubuntu Jammy like exfat-utils and some other nuances that we can't expect to work on that distro.

I will try to install Debian 11 Bullseye on the Pi4 in a little bit here and use the script.

Thanks again for your hard work on this.

**Comment by shermand100** [comment]
Thanks for trying all this out. I corrected the php-common -y typo https://github.com/shermand100/pinode-doge/commit/d6b5e2719387c809933c4f2d27dfd1ace8a9a461 so that shouldn't happen again. 

If you run into other issue do let me know. I should have more time next week to give this another run through myself (I have a spare Pi 4 to test with) and hopefully iron out those last issues.

**Comment by DogestMaximus** [comment]
I tested 1.14.6 on a Rpi4 with 8G of RAM With Armbian Jammy and the release binary works from what I can tell.  I wouldn't mind going through and just learning more about how you were able to do this because I am still learning.  It's complicated because it's forked I get that but I am still learning GitHub too so I'll also be doing some work on it and if I get somewhere with it maybe I can make it my first PR (no promises).  

Thanks again for this, it's very helpful to not just me- but the community as a whole.
